# abyss_db\docker-compose.yml

services:
  mysql:
    image: mysql:8.0
    container_name: abyss_mysql
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/abyss_db"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: abyss_db
    ports:
      - "3330:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

volumes:
  mysql_data:
